CS133Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^takai/', include('takai.urls')),
    url(r'^admin/', admin.site.urls),
]

takai/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # ex: /takai/ --> /takai/2018Spring/
    url(r'^$', RedirectView.as_view(url='/takai/2018Spring/')),

    # ex: /takai/2018Spring/
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/$', views.semester, name='semester'),

    # ex: /takai/2018Spring/140/
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/$', views.session, name='session'),

    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/enroll/$', views.enroll, name='session-enroll'),
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/teach/$', views.teach, name='session-teach'),

    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/unenroll/$', views.unenroll, name='session-unenroll'),
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/unteach/$', views.unteach, name='session-unteach'),

    # session for professors (can add TAs)
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/prof/$', views.prof, name='session-prof'),

    # session for professors - delete ta
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/prof/(?P<pk>\d+)/delete-ta/$', views.DeleteTa.as_view(), name='ta-delete'),

     # ex: /takai/2018Spring/140/edit/faculty
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/(?P<pk>\d+)/edit/faculty/$', views.UpdateSession.as_view(), name='session-faculty-edit'),

    # ex: /takai/2018Spring/140/edit/mentor
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/(?P<pk>\d+)/edit/mentorsession/$', views.UpdateMentorSession.as_view(), name='session-mentor-edit'),

     # ex: /takai/2018Spring/140/add/mentor
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/(?P<session>[0-9]+)/add/mentorsession/$', views.addMentorSession, name='session-mentor-add'),

    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/(?P<session>[0-9]+)/(?P<pk>\d+)/delete/mentorsession/$', views.DeleteMentorSession.as_view(), name='session-mentor-delete'),

    # ex: /takai/2018Spring/140/(ta_id)/edit
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/(?P<cid>[0-9]+)/(?P<pk>\d+)/edit-ta/$', views.UpdateTa, name='ta-edit'),

    # ex: /takai/010314573/
    url(r'^(?P<sid>[0-9]{8})/$', views.profile, name='profile'),

    # advanced search
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/search/$', views.adv_search, name='advsearch'),
    url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/searchresults/$', views.adv_search, name='searchresults'),

    # ex: /takai/apply
     url(r'^(?P<year>[0-9]{4})(?P<semester>[A-Za-z]+)/apply/$', views.TaApplication, name='apply'),

    url(r'^login/$', auth_views.login, name='login'),

    url(r'^admin/', admin.site.urls),

    url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),

    url(r'^signup/$', views.signup, name='signup'),
]

takai/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models

class Classes(models.Model):
    cid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return str(self.cid)

    class Meta:
        managed = True
        db_table = 'Classes'

class Mentor(models.Model):
    ta = models.ForeignKey('Ta', on_delete=models.CASCADE, blank=False, null=False) # should be renamed to ta
    session = models.ForeignKey('Session', on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return str(self.ta.student.name) + ' ' + str(self.session)

    class Meta:
        managed = True
        db_table = 'Mentor'
        unique_together = (('ta', 'session'),)


class Mentorsessions(models.Model):
    session = models.ForeignKey('Session', on_delete=models.CASCADE, blank=False, null=False)
    time = models.CharField(max_length=255) # removed primary key
    day = models.CharField(max_length=255, blank=False, null=False)
    location = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.session) + ' ' + str(self.time) + ' ' + str(self.day)

    class Meta:
        managed = True
        db_table = 'Mentorsessions'
        unique_together = (('session', 'time','day','location'),)

class Enroll(models.Model):
    student = models.ForeignKey('Students', on_delete=models.CASCADE, blank=False, null=False)
    session = models.ForeignKey('Session', on_delete=models.CASCADE, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'Enroll'
        unique_together = (('student','session'),)

    def __str__(self):
        return str(self.student.sid) + ' ' + str(self.session.theclass.cid)


class Professors(models.Model):
    fid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.CharField(max_length=255, blank=False, null=False)
    office = models.CharField(max_length=255, blank=False, null=False)
    officehours = models.CharField(db_column='officeHours', max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return ' ' + str(self.name) + ' ' + str(self.fid) + ' ' + str(self.email)

    class Meta:
        managed = True
        db_table = 'Professors'


class Session(models.Model):
    theclass = models.ForeignKey(Classes, on_delete=models.CASCADE)
    semester = models.CharField(max_length=255,blank=False, null=False)
    year = models.CharField(max_length=255, blank=False, null=False)
    classroom = models.CharField(max_length=255, blank=False, null=False)
    times = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return ' ' + str(self.theclass) + ' ' + str(self.year) + ' ' + str(self.semester)

    class Meta:
        managed = True
        db_table = 'Session'
        unique_together = (('theclass', 'semester', 'year'),)


class Students(models.Model):
    sid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=False, null=False)
    gradyear = models.TextField(db_column='gradYear', blank=False, null=False)  # Field name made lowercase. This field type is a guess.
    email = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        managed = True
        db_table = 'Students'

class Ta(models.Model):
    student = models.OneToOneField(Students, on_delete=models.CASCADE, blank=False, null=False) # from pk to one to one field
    bio = models.CharField(max_length=1500, blank=True, null=True)
    picture = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return str(self.student.name)

    class Meta:
        managed = True
        db_table = 'TA'

class Teach(models.Model):
    professor = models.ForeignKey(Professors, on_delete=models.CASCADE, blank=False, null=False)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return str(self.professor) + ' ' + str(self.session)

    class Meta:
        managed = True
        db_table = 'Teach'

class Host(models.Model):
    ta = models.ForeignKey(Ta, on_delete=models.CASCADE, blank=False, null=False) # should be mentor
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=False, null=False)
    mentorsesh = models.ForeignKey(Mentorsessions, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return str(self.ta.student.name) + ' ' + str(self.session) + ' ' + str(self.mentorsesh.time) + ' ' + str(self.mentorsesh.day)

    class Meta:
        managed = True
        db_table = 'Host'

class Application(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=False, null=False)
    semester = models.CharField(max_length=255,blank=False, null=False)
    year = models.CharField(max_length=255, blank=False, null=False)
    school = models.CharField(max_length=50, blank=False, null=False)
    major = models.CharField(max_length=100, blank=False, null=False)
    qualities = models.CharField(max_length=1500, blank=False, null=False)
    num_hours_week = models.FloatField()

    def __str__(self):
        return str(self.semester) + ' ' + str(self.year) + ' ' + str(self.school) + ' ' + str(self.major) + ' ' + str(self.qualities) + ' ' + str(self.num_hours_week)

    class Meta:
        managed = True
        db_table = 'Application'

class Availabilitycode(models.Model):
    code = models.IntegerField(primary_key=True)
    meaning = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return str(self.meaning)

    class Meta:
        managed = True
        db_table = 'Availabilitycode'

class Availability(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=False, null=False)
    availabilitycode = models.ForeignKey(Availabilitycode, models.DO_NOTHING, blank=False, null=False)

    def __str__(self):
        return str(self.availabilitycode.meaning)

    class Meta:
        managed = True
        db_table = 'Availability'

class Interestcode(models.Model):
    code = models.IntegerField(primary_key=True)
    meaning = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return str(self.meaning)

    class Meta:
        managed = True
        db_table = 'Interestcode'

class Classinterest(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=False, null=False)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=False, null=False)
    interestcode = models.ForeignKey(Interestcode, models.DO_NOTHING, blank=False, null=False)

    def __str__(self):
        return str(self.session.theclass.cid) + ' ' + str(self.interestcode.meaning)

    class Meta:
        managed = True
        db_table = 'Classinterest'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:

takai/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import BaseFormSet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from takai.models import *
from django.forms import BaseModelFormSet
import pdb


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text='Your password cannot be too similar to your other personal information, and cannot be a commonly used password. Your password must contain at least 8 characters and cannot be entirely numeric.'
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    id_number = forms.IntegerField(min_value=10000000, max_value=99999999, help_text='Please Enter your 8 digit student ID number.',
        error_messages={'min_value':'Please enter a valid ID number'})
    graduation_year = forms.IntegerField(min_value=2018)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'id_number', 'graduation_year', 'password1', 'password2', )

class UpdateProfessorInfo(forms.ModelForm):
    class Meta:
        model = Professors
        fields = ['name', 'email', 'office', 'officehours']

class UpdateSessionInfo(forms.ModelForm):
    class Meta:
        model = Session
        fields = ['theclass','semester','year','classroom','times']
        exclude = ('theclass', 'semester', 'year')

class UpdateMSInfo(forms.ModelForm):
    class Meta:
        model = Mentorsessions
        fields = ['time', 'day','location']

class AddMSInfo(forms.ModelForm):
    class Meta:
        model = Mentorsessions
        fields = ['time', 'day','location']

class UpdateTaInfo(forms.ModelForm):
    class Meta:
        model = Ta
        fields = ['student', 'bio']
        exclude = ('student',)

class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

class ClassesForm(ModelForm):
    class Meta:
        model = Classes
        fields = ['cid', 'name']

class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['school', 'major', 'qualities', 'num_hours_week']
        labels = {
            'qualities': ('What qualities do you have that make you a good student mentor?'),
            'num_hours_week': ('Maximum number of hours available per week:'),
        }

class BaseArticleFormSet(BaseFormSet):
    def clean(self):
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        sessions = []
        for form in self.forms:
            if not form.cleaned_data:
                form.add_error('interestcode', 'Did not complete form')
            else:
                session = form.cleaned_data['session']
                if session in sessions:
                    form.add_error('interestcode', 'Chose same class twice')
                sessions.append(session)

class AvailabilityForm(ModelForm):
    AVAILABILITY_CHOICES  = (
        ('1','W 1:15-2:30pm'),
        ('2','W 2:45-4:00pm' ),
        ('3','Th 1:15-2:30pm' ),
        ('4','Th 2:45-4:00pm' ),
        ('5','F 1:15-2:30pm' ),
        ('6','F 2:45-4:00pm'))

    availabilitycode= forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices = AVAILABILITY_CHOICES, label= '')
    class Meta:
        model = Availability
        fields = ['availabilitycode','student']
        exclude = ['student']

class ClassInterestForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ClassInterestForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Classinterest
        fields = ['session', 'interestcode']

        labels = {
            'interestcode': ('Interest Level:'),
            'session':('Class'),
        }

takai/templates/takai/adv_search.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/session.css' %}">

</head>

<body>
<!-- Logout Button -->
<div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>
<!-- Takai Header -->
<div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ semester }} {{ year }} </li>
</div>
<div class="page-content">

<h3> Search for TAs</h3>
<form id="searchform" method="post">
    {% csrf_token %}
     Available <select name= "availability">
       <option value="anyavail">any time</option>
       {% for availability in availabilities %}
          <option value={{availability.code}}>{{availability}}</option>
       {% endfor %}
    </select>
    and <select name = "interest">
      <option value="anyinterest">having any interest</option>
      {% for interest in interests %}
          <option value={{interest.code}}>{{interest}}</option>
      {% endfor %}
      </select>
      in mentoring for <select name = "session">
      {% for session in sessions %}
          <option value={{session.id}}>{{session}}</option>
      {% endfor %}
      </select>
    <input type="submit" value="Search">
    </form>
</div>
</body>
</html>

takai/templates/takai/apply.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{% static 'css/session.css' %}">
</head>
<body>
  <div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>

  <div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ cur_semester }} {{ cur_year }} </h1>
  </div>

<div class="page-content">
  <h2> TA Application for {{next_semester}} {{next_year}} </h2>
  <h5> <font color="red"> All fields are required </font></h5>
<p>
    <form method="post" action="">
    {% csrf_token %}
     <table>
     {{ formset1.as_table }}
     </table>
     <br>
     Please indicate your interest level for TAing each class. <br>
    {{ formset2.management_form }}
    {% for form in formset2%}
          {{form.session.label_tag}} {{form.session}}
          {{form.interestcode.label_tag}} {{form.interestcode}} <br>
    {% endfor %}

    {% if formset2.errors %}
      <li><strong><font color="red">Please make sure you select your level of interest for every class listed exactly once</font></strong></li>
    {% endif %}

    <br>
    Please select all labs times for which you are available (could be none).
     {{ formset3}}
    <input type="submit" value="Submit" >
    </form>

</p>
</div>
</body>

</html>

takai/templates/takai/edit_prof.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{% static 'css/session.css' %}">
</head>
<body>
  <div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>

  <div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ semester }} {{ year }} </h1>
  </div>

<div class="page-content">

<h2>CS{{some_class.cid}}: {{ some_class.name }} </h2>

<form action="{% url 'session-enroll' year semester some_class.cid %}" method="post">
    {% csrf_token %}
    <label for="student_id_form">Enter 8 digit student id: </label>
    <input id="student_id_form" type="text" name="student_id_field" value="Enter here.">
    <input type="submit" value="Enroll">
</form>

<ul>
{% for session in some_class.session_set.all %}
    <li>Lectures: {{ session.times }}</li>

    <form action="{% url 'session-enroll' year semester some_class.cid %}" method="post">
    {% csrf_token %}
    <label for="lecture_form">Lectures: </label>
    <input id="lecture_form" type="text" name="lecture_form" value=session.times>
    <input type="submit" value="Update">
</form>

    <li>Classroom: {{ session.classroom }}</li>
    <li>Professor(s):
        {% for prof in profs %}
            {{prof.professor.name}} <br/>
        {% endfor %}
    </li>
    <li>Office Hours:
        {% for prof in profs %}
            {{prof.professor.officehours}} <br/>
        {% endfor %}
    </li>
    <li>Mentor Sessions:
        <ul>
        {% for mentorsesh in mentorsessions %}
            <li>{{mentorsesh.mentorsesh.day}}, {{mentorsesh.mentorsesh.time}}, {{mentorsesh.mentorsesh.location}}, {{mentorsesh.student.name}} </li>
        {% endfor %}
        </ul>
    </li>
    <li>TAs:
        <ul>
        {% for ta in tas %}
            <li><a href="/takai/010314573/"> {{ta.student.student.name}}</a>: {{ta.student.bio}} </li>
        {% endfor %}
        </ul>
    </li>
{% endfor %}
</ul>

<link rel="stylesheet" type="text/css" href="mystyle.css">

</body>
</html>

takai/templates/takai/mentorsessions_add.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/session.css' %}">

</head>

<body>
<!-- Logout Button -->
<div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>
<!-- Takai Header -->
<div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ semester }} {{ year }} </li>
</div>
<div class="page-content">

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>

{% endblock %}

</div>
</body>
</html>

takai/templates/takai/mentorsessions_edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/session.css' %}">

</head>
<body>
<div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>

<div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ semester }} {{ year }} </li>
</div>

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>

{% endblock %}

</div>
</body>
</html>

takai/templates/takai/searchresults.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/session.css' %}">

</head>
<body>
<div class = "login-header" style="float:right"> Hi, {{name}}!   <a href="/takai/logout/">Logout</a> </div>

<div class="page-header">
    <h1><a href="/takai/">TAkai</a> {{ semester }} {{ year }} </li>
</div>

<div class="page-content">

<h3>Search Results</h3>

<ul>
  {% for student in results %}
    {% for thing in student %}
  <li><a href="/takai/{{thing.sid}}">{{thing.name}}</li>
    {% endfor %}
   {% endfor %}
</ul>

</div>
</body>
</html>

takai/templates/takai/session_edit_mentor_session.html
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    {{ prof_form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>

{% endblock %}